title: Translator Settings
tabs:
  main:
    display: Main
    sections:
      - fields:
          - handle: translator
            field:
              type: select
              display: Translator
              options:
                deepl: DeepL
              placeholder: 'Choose a translator'
              clearable: true
              required: false
              default: deepl

          - handle: free_version 
            field:
              type: toggle
              display: Free Version
              instructions: 'Enable this option if you are using the free version of the translation service.'
              default: false 

          - handle: api_key
            field:
              type: text
              display: API Key
              instructions: 'Enter your API key for translation services'
              required: true
              default: key